version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/kt_5th_miniproject
    overwrite: true

permissions:
  - object: /home/ec2-user/kt_5th_miniproject
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 1200
      runas: root
